M48
; DRILL file {KiCad 9.0.0} date 2025-03-24T22:57:18+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-24T22:57:18+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0260
%
G90
G05
T2
X3.4732Y-2.4409
X3.7008Y-2.4409
T3
X3.7984Y-4.9924
T1
G00X3.5114Y-4.9924
M15
G01X3.4949Y-4.9924
M16
G05
M30
