M48
; DRILL file {KiCad 9.0.0-9.0.0-2~ubuntu22.04.1} date 2025-03-27T09:55:17+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-27T09:55:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0-9.0.0-2~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.660
%
G90
G05
T2
X88.22Y-62.0
X94.0Y-62.0
T3
X96.48Y-126.807
T1
G00X89.19Y-126.807
M15
G01X88.77Y-126.807
M16
G05
M30
